name: Example CICD Pipeline

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        deploy:
          description: 'Deploy the project'
          required: true
          default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name:  Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build Project
        run: npm run build
        env:
          PATH: ./localhost


      # Dockerize project
      - name: Dockerize Build
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  
    # Add a deployment job that triggers deploy.yml upon completion
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'true'
    steps:
      - name: Trigger deploy workflow
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflowRuns } = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file: 'deploy.yml',
              status: 'success',
            });
            if (workflowRuns.total_count === 0) {
              await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_file: 'deploy.yml',
                ref: 'main', // or any other branch you want to trigger deploy on
                inputs: {} // You can pass inputs to your deploy workflow if needed
              });
            }